// Dados sintéticos gerados automaticamente
// Baseado nas distribuições do artigo do Hospital Albert Einstein

export const syntheticPatients = [
  {
    name: 'Pedro Magro',
    sex: 'F',
    birthYear: 1968,
    records: [
      {
        year: 2023,
        heightCm: 154.4,
        weightKg: 48.0,
        bmi: 20.11,
        waistCm: 60.4,
        systolicBp: 107,
        diastolicBp: 79,
        triglyceridesMgDl: 108,
        hdlMgDl: 60,
        ldlMgDl: 89,
        totalCholesterolMgDl: 170,
        fastingGlucoseMgDl: 81,
        astUL: 27,
        altUL: 39,
        ggtUL: 28,
        physicalActivityLevel: 'moderate',
        smokingStatus: 'never',
        auditScore: 15,
        bdiScore: 19,
        isOnAntihypertensive: false,
        isOnAntidiabetic: false,
        isOnLipidLowering: false,
        hasMetabolicSyndrome: false,
        diseaseCodes: [],
      },
      {
        year: 2024,
        heightCm: 154.4,
        weightKg: 48.53749257443121,
        bmi: 20.36,
        waistCm: 60.829994059544966,
        systolicBp: 104,
        diastolicBp: 75,
        triglyceridesMgDl: 115,
        hdlMgDl: 62,
        ldlMgDl: 79,
        totalCholesterolMgDl: 165,
        fastingGlucoseMgDl: 81,
        astUL: 27,
        altUL: 39,
        ggtUL: 28,
        physicalActivityLevel: 'moderate',
        smokingStatus: 'never',
        auditScore: 15,
        bdiScore: 19,
        isOnAntihypertensive: false,
        isOnAntidiabetic: false,
        isOnLipidLowering: false,
        hasMetabolicSyndrome: false,
        diseaseCodes: [],
      },
    ],
  },
  {
    name: 'Roberto Obeso',
    sex: 'M',
    birthYear: 1968,
    records: [
      {
        year: 2023,
        heightCm: 179.8,
        weightKg: 114.8,
        bmi: 35.51,
        waistCm: 128.5,
        systolicBp: 136,
        diastolicBp: 98,
        triglyceridesMgDl: 104,
        hdlMgDl: 55,
        ldlMgDl: 93,
        totalCholesterolMgDl: 169,
        fastingGlucoseMgDl: 101,
        astUL: 21,
        altUL: 26,
        ggtUL: 31,
        physicalActivityLevel: 'inactive',
        smokingStatus: 'never',
        auditScore: 5,
        bdiScore: 3,
        isOnAntihypertensive: true,
        isOnAntidiabetic: false,
        isOnLipidLowering: false,
        hasMetabolicSyndrome: true,
        diseaseCodes: ["I10"],
      },
      {
        year: 2024,
        heightCm: 179.8,
        weightKg: 115.14679018733152,
        bmi: 35.62,
        waistCm: 128.7774321498652,
        systolicBp: 145,
        diastolicBp: 101,
        triglyceridesMgDl: 92,
        hdlMgDl: 52,
        ldlMgDl: 84,
        totalCholesterolMgDl: 155,
        fastingGlucoseMgDl: 97,
        astUL: 21,
        altUL: 26,
        ggtUL: 31,
        physicalActivityLevel: 'inactive',
        smokingStatus: 'never',
        auditScore: 5,
        bdiScore: 3,
        isOnAntihypertensive: true,
        isOnAntidiabetic: false,
        isOnLipidLowering: false,
        hasMetabolicSyndrome: false,
        diseaseCodes: ["I10"],
      },
    ],
  },
  {
    name: 'Ana Transformação',
    sex: 'F',
    birthYear: 1972,
    records: [
      {
        year: 2023,
        heightCm: 161.5,
        weightKg: 68.3,
        bmi: 26.19,
        waistCm: 78.8,
        systolicBp: 134,
        diastolicBp: 78,
        triglyceridesMgDl: 125,
        hdlMgDl: 49,
        ldlMgDl: 119,
        totalCholesterolMgDl: 193,
        fastingGlucoseMgDl: 112,
        astUL: 19,
        altUL: 33,
        ggtUL: 73,
        physicalActivityLevel: 'moderate',
        smokingStatus: 'current',
        auditScore: 11,
        bdiScore: 21,
        isOnAntihypertensive: false,
        isOnAntidiabetic: true,
        isOnLipidLowering: false,
        hasMetabolicSyndrome: true,
        diseaseCodes: ["E11"],
      },
      {
        year: 2024,
        heightCm: 161.5,
        weightKg: 67.34581497758343,
        bmi: 25.82,
        waistCm: 78.03665198206674,
        systolicBp: 136,
        diastolicBp: 80,
        triglyceridesMgDl: 130,
        hdlMgDl: 50,
        ldlMgDl: 119,
        totalCholesterolMgDl: 196,
        fastingGlucoseMgDl: 106,
        astUL: 19,
        altUL: 33,
        ggtUL: 73,
        physicalActivityLevel: 'moderate',
        smokingStatus: 'current',
        auditScore: 11,
        bdiScore: 21,
        isOnAntihypertensive: false,
        isOnAntidiabetic: true,
        isOnLipidLowering: false,
        hasMetabolicSyndrome: false,
        diseaseCodes: ["E11"],
      },
    ],
  },
  {
    name: 'Carlos Moderado',
    sex: 'M',
    birthYear: 1973,
    records: [
      {
        year: 2023,
        heightCm: 187.2,
        weightKg: 110.0,
        bmi: 31.39,
        waistCm: 111.6,
        systolicBp: 118,
        diastolicBp: 76,
        triglyceridesMgDl: 297,
        hdlMgDl: 44,
        ldlMgDl: 107,
        totalCholesterolMgDl: 211,
        fastingGlucoseMgDl: 78,
        astUL: 12,
        altUL: 71,
        ggtUL: 25,
        physicalActivityLevel: 'low',
        smokingStatus: 'never',
        auditScore: 5,
        bdiScore: 4,
        isOnAntihypertensive: true,
        isOnAntidiabetic: false,
        isOnLipidLowering: true,
        hasMetabolicSyndrome: false,
        diseaseCodes: ["I10"],
      },
      {
        year: 2024,
        heightCm: 187.2,
        weightKg: 112.05539350131156,
        bmi: 31.98,
        waistCm: 113.24431480104924,
        systolicBp: 127,
        diastolicBp: 74,
        triglyceridesMgDl: 266,
        hdlMgDl: 39,
        ldlMgDl: 116,
        totalCholesterolMgDl: 208,
        fastingGlucoseMgDl: 82,
        astUL: 12,
        altUL: 71,
        ggtUL: 25,
        physicalActivityLevel: 'low',
        smokingStatus: 'never',
        auditScore: 5,
        bdiScore: 4,
        isOnAntihypertensive: true,
        isOnAntidiabetic: false,
        isOnLipidLowering: true,
        hasMetabolicSyndrome: true,
        diseaseCodes: ["I10"],
      },
    ],
  },
  {
    name: 'Lucia Cardíaca',
    sex: 'F',
    birthYear: 1963,
    records: [
      {
        year: 2023,
        heightCm: 161.0,
        weightKg: 57.6,
        bmi: 22.22,
        waistCm: 60.7,
        systolicBp: 138,
        diastolicBp: 79,
        triglyceridesMgDl: 117,
        hdlMgDl: 68,
        ldlMgDl: 119,
        totalCholesterolMgDl: 210,
        fastingGlucoseMgDl: 76,
        astUL: 17,
        altUL: 27,
        ggtUL: 32,
        physicalActivityLevel: 'low',
        smokingStatus: 'never',
        auditScore: 8,
        bdiScore: 17,
        isOnAntihypertensive: false,
        isOnAntidiabetic: false,
        isOnLipidLowering: false,
        hasMetabolicSyndrome: false,
        diseaseCodes: [],
      },
      {
        year: 2024,
        heightCm: 161.0,
        weightKg: 54.99562379639877,
        bmi: 21.22,
        waistCm: 60.0,
        systolicBp: 135,
        diastolicBp: 74,
        triglyceridesMgDl: 131,
        hdlMgDl: 73,
        ldlMgDl: 109,
        totalCholesterolMgDl: 209,
        fastingGlucoseMgDl: 76,
        astUL: 17,
        altUL: 27,
        ggtUL: 32,
        physicalActivityLevel: 'low',
        smokingStatus: 'never',
        auditScore: 8,
        bdiScore: 17,
        isOnAntihypertensive: false,
        isOnAntidiabetic: false,
        isOnLipidLowering: false,
        hasMetabolicSyndrome: false,
        diseaseCodes: [],
      },
    ],
  },
];
